### PR TITLE
Group failures by file

### PR DESCRIPTION
**Pull request by mrjoops**
Since the code suggests an intent to group the errors by file (with the creation of the `$fileErrors` array) but doesn't achieve this intent, let's do it !

I did some refactoring too and committed atomically so you can follow each step easily.

PHPStan, PHPCS and PHPUnit tests are passing.

I use Gitmoji if you ask (see https://gitmoji.carloscuesta.me/).

My CI platform thank you for your contribution ! Keep up the good work !

### CODE REVIEW

**Comment by mavimo** [comment]
@mrjoops thx for your contribution!!!

At the begin we don't plan to group using file since there are some issue on the JUnit plugin used by Jenkins X that do not allow to see all errors, I'll check ASAP!

PS: what CI tool do you use?

**Comment by mavimo** [comment]
@mrjoops after some test the issue still here, reproducible also on bitbucket:

## CLI
image

## Bitbucket (3 errors, only 2 visible)
image

## Jenkins Blue ocean (3 errors, only 2 visible)
image

You can see the repo I used for test on https://github.com/mavimo/test-phpstan-junit, do you know if there is some part missing from the current JUnit definition?

PS: i really like to include this feature if we can find a way to make it work also on this tools (I think that is a must have for DX)

**Comment by mrjoops** [comment]
The closest thing to a JUnit report format spec I found is https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

**Comment by mavimo** [comment]
@mrjoops is the same doc I use as reference for the initial implementation, at the begin we start to group by file but than we have issue with tools that display the result (eg Jenkins + JUnit & Bitbucket).
I'm considering to create different output plugin (with / without grouping feature), can you give me more context on tool do you use to process the phpstan-junit output and how the info are presented? Thx!!

**Comment by mrjoops** [comment]
After trying to validate the XML generated by the plugin against the schema, it seems that multiple failure elements inside a testcase is invalid, so forget about grouping.

By the way the XML doesn't validate either before the grouping... so let's forget completely about this PR (_these aren't the droids you're looking for_), I'll make another one to fix the XML.

**Comment by mrjoops** [comment]
The PR #30 has been created.

**Comment by mavimo** [comment]
@mrjoops I'm going to close this PR since is replaced by #30

**Pull request closed without merging**
