### PR TITLE
XML Schema conformance

### PR DESCRIPTION
**Pull request by mrjoops**
Now the generated XML conforms to the XML Schema found here: https://github.com/windyroad/JUnit-Schema.

I did some refactoring too and committed atomically so you can follow each step easily.

PHPStan, PHPCS and PHPUnit tests are passing.

I use Gitmoji if you ask (see https://gitmoji.carloscuesta.me/).

### CODE REVIEW

**Comment by mavimo** [comment]
@mrjoops thx (again) fr your contribution 😄 

After few investigation I see a "pseudo-official" XSD definition for JUnit file format (is the definition reported in the `junit-team` organisation under `junit5` project), you can see it at https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd

I suggest a few changes on the this PR:
 - Change XSD definition file (i suggest to use [this one](https://raw.githubusercontent.com/junit-team/junit5/5caf217676e85a51aabec736fce7cadf687a299d/platform-tests/src/test/resources/jenkins-junit.xsd) in order to make it immutable)
 - Remove attributes that are not needed, as you can see some attributes are optional, but the definition reported from the XSD you're used as source-of-truth indicate that are required (that are not)
 - Include a test to validate the result file using the XSD for files generated from this plugin

@mrjoops WDYT? Do you have time for this small changes or do you prefer that I send a PR on your repo to merge to this PR?

**Comment by mrjoops** [comment]
I changed the target XSD, removed optional attributes and elements, and added a test to validate the schema.

**Comment by mavimo** [comment]
@mrjoops thx for your contribution!

**Comment by mrjoops** [comment]
On a side note, you added this to the v0.2.2 milestone but 0.2.2 had already been tagged 9 days ago.

**Comment by mavimo** [comment]
@mrjoops right, sorry, was my mistake!

I planned to release v0.2.3 (in few days), once I switch from github actions to github workflow.

**Pull request merged**
